### ISSUE TITLE
Problem generating confusion_matrix.print_stats()

### ISSUE THREAD

**Issue by lamdawr** [pandas-ml/pandas_confusion#15]
I ran `ConfusionMatrix` from `pandas_confusion` and had no problem in generating the confusion matrix but when I try to print the stats using `print_stats()`, I get error saying `cannot convert float NaN to integer', u'occurred at index 6`

```python
from pandas_confusion import ConfusionMatrix
import pandas as pd
from sklearn import metrics


cd1 = pd.read_csv('d:\classified.csv', names = ["file", "cc1","m"])

y_true =  cd1.m
y_pred = cd1.cc1


confusion_matrix = ConfusionMatrix(y_true, y_pred)
print("Confusion matrix:\n%s" % confusion_matrix)
confusion_matrix.plot()

confusion_matrix.print_stats()

Traceback (most recent call last):

  File "<ipython-input-38-f2fd91f0d787>", line 1, in <module>
    runfile('D:/stats_rough2.py', wdir='D:/Git/')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/stats_rough2.py", line 22, in <module>
    confusion_matrix.print_stats()

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 477, in print_stats
    print(self._str_stats(lst_stats))

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 460, in _str_stats
    stats = self.stats(lst_stats)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 423, in stats
    d_stats['overall'] = self.stats_overall

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 340, in stats_overall
    d_class_agreement = class_agreement(df)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\stats.py", line 57, in class_agreement
    num = df[df>1].dropna(axis=[0,1], thresh=1).applymap(lambda n: choose(np.int64(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4250, in applymap
    return self.apply(infer)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4157, in _apply_standard
    results[i] = func(v)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4248, in infer
    return lib.map_infer(x.asobject, func)

  File "pandas\src\inference.pyx", line 1088, in pandas.lib.map_infer (pandas\lib.c:62658)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\stats.py", line 57, in <lambda>
    num = df[df>1].dropna(axis=[0,1], thresh=1).applymap(lambda n: choose(np.int64(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2

ValueError: ('cannot convert float NaN to integer', u'occurred at index 6')
```

**Comment by scls19fr** [comment]
Could you send `classified.csv` file ? or create some code to mimic this issue ?

I also suggest to have a look at `cd1.dtypes`

**Comment by lamdawr** [comment]
0,9,9
1,9,9
2,18,18
3,9,9
4,71,71
5,22,22
6,71,71
7,22,22
8,71,71
9,9,9
10,9,9
11,9,9
12,9,9
13,4,75
14,9,9
15,9,9
16,9,9
17,9,9
18,9,9
19,9,9
20,9,9
21,22,22
22,12,12
23,4,75
24,71,71
25,88,88
26,22,22
27,88,88
28,88,88
29,88,88
30,88,88
31,9,9
32,9,9
33,82,82
34,68,68
35,81,81
36,71,71
37,71,71
38,9,9
39,9,9
40,9,9
41,71,71
42,9,9
43,71,71
44,9,9
45,71,71
46,22,22
47,22,22
48,71,71
49,4,75
50,9,9
51,9,9
52,9,9
53,78,78
54,9,9
55,71,71
56,22,22
57,71,71
58,12,12
59,78,78
60,82,82
61,9,9
62,28,28
63,9,9
64,4,75
65,9,9
66,9,9
67,9,9
68,22,22
69,9,9
70,9,9
71,22,22
72,9,9
73,9,9
74,71,71
75,30,30
76,22,22
77,28,28
78,12,12
79,82,82
80,71,71
81,71,71
82,71,71
83,71,71
84,71,71
85,71,71
86,78,78
87,9,9
88,82,82
89,1,1
90,22,22
91,71,71
92,9,9
93,22,22
94,22,22
95,68,68
96,9,9
97,9,9
98,28,28
99,200,200
100,9,9
101,9,9
102,9,9
103,9,9
104,9,9
105,9,9
106,9,9
107,9,9
108,9,9
109,9,9
110,9,9
111,9,9
112,9,9
113,9,9
114,9,9
115,82,82
116,9,9
117,9,9
118,9,9
119,6,6
120,9,9
121,9,9
122,9,9
123,9,9
124,9,9
125,9,9
126,9,9 ... something like that for 30k lines

**Comment by scls19fr** [comment]
It seems to be fixed now

Install last developper branch using

```
pip install git+https://github.com/pandas-ml/pandas_confusion
```

Feel free to reopen in case of problem

**Comment by lamdawr** [comment]
I got this when I tried with the new branch 

Traceback (most recent call last):

  File "<ipython-input-1-b72feaa9344d>", line 16, in <module>
    confusion_matrix.print_stats()

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 477, in print_stats
    print(self._str_stats(lst_stats))

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 460, in _str_stats
    stats = self.stats(lst_stats)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 423, in stats
    d_stats['overall'] = self.stats_overall

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\__init__.py", line 340, in stats_overall
    d_class_agreement = class_agreement(df)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\stats.py", line 57, in class_agreement
    num = df[df>1].dropna(axis=[0,1], thresh=1).applymap(lambda n: choose(np.int64(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4250, in applymap
    return self.apply(infer)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4157, in _apply_standard
    results[i] = func(v)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 4248, in infer
    return lib.map_infer(x.asobject, func)

  File "pandas\src\inference.pyx", line 1088, in pandas.lib.map_infer (pandas\lib.c:62658)

  File "C:\Anaconda2\lib\site-packages\pandas_confusion\stats.py", line 57, in <lambda>
    num = df[df>1].dropna(axis=[0,1], thresh=1).applymap(lambda n: choose(np.int64(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2

ValueError: ('cannot convert float NaN to integer', u'occurred at index 6')

**Comment by scls19fr** [comment]
Please use 3 backquotes for code / traceback

```like this```

That's odd because you shouldn't have 

`num = df[df>1].dropna(axis=[0,1], thresh=1).applymap(lambda n: choose(np.int64(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2`

but

```
    num = df[df > 1].dropna(axis=[0, 1], thresh=1).applymap(lambda n: choose(int_nan(n), 2)).sum().sum() - np.float64(nis2 * njs2) / n2
```

I think you didn't correctly uninstall package.

try

```
pip uninstall pandas_confusion
```

run IPython

`from pandas_confusion import ConfusionMatrix`

should raise

```
In [1]: from pandas_confusion import ConfusionMatrix
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c195ba2cff65> in <module>()
----> 1 from pandas_confusion import ConfusionMatrix

ImportError: No module named 'pandas_confusion'
```

After reinstall using

```
pip install git+https://github.com/pandas-ml/pandas_confusion
```

**Comment by lamdawr** [comment]
Thank you very much ! Works well now.

**Comment by scls19fr** [comment]
`ConfusionMatrix` is now part of https://github.com/pandas-ml/pandas-ml
